name: kakaollama
description: "KakaoTalk but for chatting with your best friend Llama 3"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  flutter_animate: ^4.5.0
  flutter_markdown: ^0.7.3+2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.14.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/kakaollama_logo.png"
